include:
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/packaging.yml'
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/packaging-arm.yml'
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - pre-package
  - package
  - post-package
  - deploy

.docker-build:
  variables:
    COMPOSE_FILE_NAME: docker-compose.tts-api.yml
    IMAGE_NAME_VARIABLE_NAME: TTS_API_IMAGE_NAME
    IMAGE_TAG_VARIABLE_NAME: TTS_API_IMAGE_TAG

.deploy:
  variables:
    FORCE_DOCKER_COMPOSE: 1
    COMPOSE_FILE: docker-compose.tts-api.yml
    SERVICES_TO_CHECK: ${CI_PROJECT_NAME}
  environment:
    name: environment/tts-api

.deploy-caddy:
  variables: &deploy-caddy-variables
    FORCE_DOCKER_COMPOSE: 0
    COMPOSE_FILE: docker-compose.caddy.yml
    SERVICES_TO_CHECK: ${CI_PROJECT_NAME}_caddy
  environment: &deploy-caddy-environment
    name: environment/caddy
    url: https://tts.${DD_TRAEFIK_DOMAIN}

deploy-caddy-branch:
  extends: deploy-branch
  variables:
    <<: *deploy-caddy-variables
  environment: *deploy-caddy-environment

deploy-caddy-tag:
  extends: deploy-tag
  variables:
    <<: *deploy-caddy-variables
  environment: *deploy-caddy-environment
