version: '2.4'

services:
  tts-api:
    image: ${TTS_API_IMAGE_NAME:-pedroetb/tts-api}:${TTS_API_IMAGE_TAG:-latest}
    build:
      context: ${BUILD_CONTEXT:-..}
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        NODE_IMAGE_TAG:
        APT_REPOSITORY:
        GOOGLE_SPEECH_VERSION:
        GTTS_VERSION:
        ESPEAK_VERSION:
        FESTIVAL_VERSION:
        WGET_VERSION:
        PYTHON3_VERSION:
        PYTHON3_PIP_VERSION:
        PYTHON3_SETUPTOOLS_VERSION:
        PYTHON3_WHEEL_VERSION:
        SOX_VERSION:
        LIBSOX_FMT_MP3_VERSION:
        FESTVOX_ELLPC11K_VERSION:
        PORT:
    container_name: ${CONTAINER_NAME}
    environment:
      PORT:
    networks:
      tts-api-net:
    devices:
      - ${AUDIO_DEVICE:-/dev/snd}
    restart: always
    cpus: '${CPUS:-0.5}'
    mem_limit: ${MEM_LIMIT:-64M}
    mem_reservation: ${MEM_RESERVATION:-32M}

networks:
  tts-api-net:
    name: ${TTS_API_NET_NAME}
    driver: ${TTS_API_NET_DRIVER}
    external: true
