version: '3.7'

services:
  tts-api:
    image: ${IMAGE_NAME:-pedroetb/tts-api}:${IMAGE_TAG:-latest}
    build:
      context: ..
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        NODE_IMAGE_TAG:
        APT_REPOSITORY:
        GOOGLE_SPEECH_VERSION:
        GTTS_VERSION:
        ESPEAK_VERSION:
        FESTIVAL_VERSION:
        PYTHON3_VERSION:
        PYTHON3_PIP_VERSION:
        PYTHON3_SETUPTOOLS_VERSION:
        PYTHON3_WHEEL_VERSION:
        SOX_VERSION:
        LIBSOX_FMT_MP3_VERSION:
        FESTVOX_ELLPC11K_VERSION:
        PORT:
    container_name: ${CONTAINER_NAME}
    environment:
      PORT:
    networks:
      tts-api-net:
    devices:
      - ${AUDIO_DEVICE:-/dev/snd}
    restart: always

networks:
  tts-api-net:
    name: ${TTS_API_NET_NAME:-tts-api-net}
    external: true
