version: '3.7'

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:${IMAGE_TAG:-alpine}
    networks:
      - caddy-net
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        traefik.port: "2015"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: Host:tts.${PUBLIC_HOSTNAME}
        traefik.backend: tts-api
      restart_policy:
        delay: 10s
        window: 30s
      resources:
        limits:
          cpus: '0.1'
          memory: 32M
        reservations:
          memory: 26M

networks:
  caddy-net:
    name: caddy-net
    driver: overlay
    attachable: true

  traefik-net:
    external: true
