version: '2.4'

services:
  tts-api:
    image: pedroetb/tts-api:${IMAGE_TAG:-latest}
    networks:
      - caddy-net
    devices:
      - /dev/snd
    healthcheck:
      test: wget --spider -S -t 3 http://localhost:${PORT}
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      caddy.address: ":2015"
      caddy.targetport: "${PORT}"
      caddy.tls: "off"
    restart: on-failure
    mem_limit: 64M
    mem_reservation: 52M

networks:
  caddy-net:
    external: true
